name: bbcfirsttvguide

on:
  schedule:
    - cron: "0 5 * * *" # GitHub uses UTC
  push:
    paths:
      - '**.yml'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install required PowerShell modules
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module UncommonSense.BbcTvGuide, UncommonSense.iCalendar -Scope CurrentUser

      - name: Update calendar file
        shell: pwsh
        run: |
          Set-StrictMode -Version Latest
          $TimeZone = [System.TimeZoneInfo]::FindSystemTimeZoneById('Europe/Amsterdam')          
          Get-BbcTvGuide -Channel bbc-first
          | ForEach-Object { $_ | Add-Member -NotePropertyName StartAmsterdam -NotePropertyValue ([System.TimeZoneInfo]::ConvertTimeFromUtc($_.StartUtc, $TimeZone)) -PassThru }
          | ForEach-Object { $_ | Add-Member -NotePropertyName EndAmsterdam -NotePropertyValue ([System.TimeZoneInfo]::ConvertTimeFromUtc($_.EndUtc, $TimeZone)) -PassThru } 
          | Where-Object { $_.StartAmsterdam.Hour -lt 23 }    
          | Where-Object { $_.EndAmsterdam.Hour -ge 19 -or $_.EndAmsterdam.Date -gt $_.StartAmsterdam.Date }
          | ForEach-Object { New-CalendarEvent -Start ($_.StartUtc) -End ($_.EndUtc) -Summary "BBC First: $($_.FullTitle)" -Description ($_.FullSynopsis) }
          | Export-Calendar -Name 'BBC First TV Guide' -Path ./bbc-first.ics

      - name: Push changes to git repo
        run: |
          git config --global user.name 'Elsbeth Nieuwenhuizen'
          git config --global user.email 'elsbethnieuwenhuizen@hotmail.com'
          git remote set-url origin https://x-access-token:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}
          git pull
          git add ./bbc-first.ics
          git commit -am 'Updated BBC First TV Guide' || echo "No changes to commit"
          git push
